# Generated by Django 3.2 on 2021-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('comment', models.TextField(default='')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
